IsTakip/Controllers/SirketController.cs
using IsTakip.Models;
using IsTakip.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsTakip.Controllers
{
    public class SirketController : Controller
    {
        DbIsTakipEntities1 db = new DbIsTakipEntities1();
        GenericRepository<TBL_PERSON> repo = new GenericRepository<TBL_PERSON>();
        public void UserSession()
        {
            string personelAd = Convert.ToString(Session["PersonelAdSoyad"?.ToString() ?? "Kullanıcı tanımlanmamış"]);
            int birimID = Convert.ToInt32(Session["PersonelBirimID"]);

            var birim = (from b in db.TBL_BIRIMLER where b.ID == birimID select b).FirstOrDefault();

            if (birim != null && birim.birimAd != null)
                ViewBag.birimAd = birim.birimAd;
            else
                ViewBag.birimAd = "Birim adı yok";

            ViewBag.personelName = personelAd;
        }

        public ActionResult Index()
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
                return RedirectToAction("Index", "Login");

            return View();
        }

        //Personel işlemleri
        [HttpGet]
        public ActionResult PersonelListele()
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            var model = new PersonelViewModel
            {
                Yoneticiler = db.TBL_PERSON.Where(x => x.personelYetkiID == 1 && x.personelAktiflik == true).ToList(),
                Personeller = db.TBL_PERSON.Where(x => x.personelYetkiID == 2 && x.personelAktiflik == true).ToList()
            };

            return View(model);
        }


        [HttpPost]
        public ActionResult PersonelSil(int id)
        {
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            var personel = db.TBL_PERSON.FirstOrDefault(x => x.ID == id);

            if (personel != null)
            {
                personel.personelAktiflik = false;
                db.SaveChanges();
            }

            return RedirectToAction("PersonelListele");
        }

        [HttpGet]
        public ActionResult PersonelDuzenle(int id)
        {
            UserSession();

            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            TBL_PERSON p = repo.Find(x => x.ID == id);
            UserSession();
            return View(p);
        }

        [HttpPost]
        public ActionResult PersonelDuzenle(TBL_PERSON p)
        {
            TBL_PERSON w = repo.Find(x => x.ID == p.ID);
            w.personelAdSoyad = p.personelAdSoyad;
            w.personelUsername = p.personelUsername;
            w.personelPasswd = p.personelPasswd;
            w.personelYetkiID = p.personelYetkiID;
            repo.TUpdate(w);

            return RedirectToAction("PersonelListele");
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(string personelAdSoyad, string personelUsername, string personelPasswd, int? personelYetkiID, int personelBirimID)
        {
            int personelYetkiId = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiId != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            TBL_PERSON personel = new TBL_PERSON();

            if (!personelYetkiID.HasValue)
                personelYetkiID = 1;


            personel.personelAdSoyad = personelAdSoyad;
            personel.personelUsername = personelUsername;
            personel.personelPasswd = personelPasswd;
            personel.personelYetkiID = personelYetkiID.Value;
            personel.personelBirimID = personelBirimID;
            personel.personelAktiflik = true;

            db.TBL_PERSON.Add(personel);
            db.SaveChanges();

            return RedirectToAction("PersonelListele");
        }
        [HttpGet]
        public ActionResult MesajGonder()
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);
            if (personelYetkiID != 1)
                return RedirectToAction("Index", "Login");

            int birimID = Convert.ToInt32(Session["PersonelBirimID"]);
            var calisanlar = (from p in db.TBL_PERSON where p.personelBirimID == birimID && p.personelYetkiID == 2 && p.personelAktiflik == true select p).ToList();

            ViewBag.personel = calisanlar;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MesajGonder(TBL_MESAJLAR mesaj)
        {
            mesaj.Sender = Convert.ToString(Session["PersonelAdSoyad"]);

            mesaj.SendTime = DateTime.Now;
            if (mesaj.IsOriginal != true)
                mesaj.IsOriginal = true;

            if (int.TryParse(Request.Form["PersonelID"], out int userID))
            {
                if (userID == 0)
                    mesaj.PersonelID = null;
                else
                    mesaj.PersonelID = userID;
            }

            db.TBL_MESAJLAR.Add(mesaj);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult MesajListele()
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            var mesajlar = db.TBL_MESAJLAR
            .Join(db.TBL_PERSON,
                  mesaj => mesaj.PersonelID,
                  personel => personel.ID,
                  (mesaj, personel) => new MesajViewModel
                  {
                      ID = mesaj.ID,
                      Header = mesaj.Header,
                      Context = mesaj.Context,
                      Sender = mesaj.Sender,
                      SendTime = mesaj.SendTime,
                      IsOriginal = mesaj.IsOriginal,
                      PersonelID = mesaj.PersonelID,
                      PersonelAdi = personel.personelAdSoyad
                  })
            .ToList();

            return View(mesajlar);
        }
        public ActionResult MesajSil(int id)
        {
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            var mesaj = db.TBL_MESAJLAR.Find(id);
            if (mesaj != null)
            {
                db.TBL_MESAJLAR.Remove(mesaj);
                db.SaveChanges();
            }

            return RedirectToAction("MesajListele");
        }
        [HttpGet]
        public ActionResult MesajDuzenle(int id)
        {
            UserSession();
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            var mesaj = db.TBL_MESAJLAR.Find(id);
            return View(mesaj);
        }
        [HttpPost]
        public ActionResult MesajDuzenle(TBL_MESAJLAR m)
        {
            int personelYetkiID = Convert.ToInt32(Session["PersonelYetkiID"]);

            if (personelYetkiID != 1)
            {
                return RedirectToAction("Index", "Login");
            }

            TBL_MESAJLAR w = db.TBL_MESAJLAR.Where(x => x.ID == m.ID).Single();
            w.Header = m.Header;
            w.Context = m.Context;
            w.SendTime = DateTime.Now;
            w.IsOriginal = false;
            db.SaveChanges();

            return RedirectToAction("MesajListele");
        }
    }
}

IsTakip/Views/Sirket/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<h2 class="text-center">Şirket Yönetim Sistemi</h2>
<br />

<div class="container">
    <div class="row">
        <div class="card col-4" style="width: 520px;margin-left: 20px ;border-radius: 12px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);">
            <div class="card-body">
                <div>
                    <h5 class="text-center">Personel Yönetimi</h5>
                    <br />
                    <div class="container">
                        <div class="row">
                            <div class="col-5">
                                <a href="/Sirket/PersonelListele/" class="btn btn-primary" style="width:150px">
                                    <i class="fa-solid fa-list-ul"></i>
                                    Personeller
                                </a>
                                <a href="#" class="btn btn-primary mt-2" style="width:150px">
                                    <i class="fas fa-tachometer-alt"></i>
                                    Çalışan istatistikleri
                                </a>
                            </div>
                            <div class="col-5 ms-auto">
                                <a href="/Sirket/MesajListele/" class="btn btn-primary" style="width:150px">
                                    <i class="fa-solid fa-list-ul"></i>
                                    Mesajlar
                                </a>
                                <a href="/Sirket/MesajGonder/" class="btn btn-primary mt-2" style="width:150px">
                                    <i class="fa-regular fa-message"></i>
                                    Çalışanlara ileti gönder
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card col-4 ms-auto" style="width: 520px;margin-right: 20px ;border-radius: 12px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);">
            <div class="card-body">
                <div>
                    <h5 class="text-center">Gelir-Gider Takibi</h5>
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

IsTakip/Views/Sirket/MesajDuzenle.cshtml
@model IsTakip.Models.TBL_MESAJLAR

@{
    ViewBag.Title = "MesajDuzenle";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<br />
<h2 class="text-center">Mesajı Düzenle</h2>
<br />
<br />

<div class="container">
    @using (Html.BeginForm("MesajDuzenle", "Sirket", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.LabelFor(x => x.Header, "Başlık")
        @Html.TextBoxFor(x => x.Header, new { @class="form-control"})
        <br />
        @Html.LabelFor(x => x.Context, "Mesaj")
        @Html.TextBoxFor(x => x.Context, new { @class = "form-control" })
        <br />

        <button type="submit" class="btn btn-success">Kaydet</button>

        <p><i style="font-size:12px; user-select:none">Kaydet tuşuna basıldıktan sonra mesaj orjinalliğini kaybedecekdir.</i></p>
        }
    </div>

IsTakip/Views/Sirket/MesajGonder.cshtml
@model IsTakip.Models.TBL_MESAJLAR


@{
    ViewBag.Title = "MesajGonder";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

@using (Html.BeginForm("MesajGonder", "Sirket", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <h2 class="text-center">Çalışanlara Mesaj Gönder</h2>
    <br />

    @Html.LabelFor(x => x.Header, "Mesaj başlığı")
    @Html.TextBoxFor(x => x.Header, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Context, "Mesaj")
    @Html.TextBoxFor(x => x.Context, new { @class = "form-control" })
    <br />

    if (ViewBag.personel == null)
    {
        <option>Personel listesi bulunamadı.</option>
    }
    else
    {
        <select class="form-select" name="PersonelID">
            <option value="0">Tüm personeller</option>
            @foreach (var x in ViewBag.personel)
            {
                <option value="@x.ID">@x.personelAdSoyad</option>
            }
        </select>
    }

    <br />

    <button type="submit" class="btn btn-primary">Gönder</button>
}

IsTakip/Views/Sirket/MesajListele.cshtml
@using IsTakip.Models
@model List<MesajViewModel>

@{
    ViewBag.Title = "MesajListele";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<h2 class="text-center">Gönderilmiş Mesajlar</h2>

<div class="container">
    <table class="table">
        <tr>
            <th>#</th>
            <th>Başlık</th>
            <th>Mesaj</th>
            <th>Gönderen</th>
            <th>Tarih</th>
            <th>Sil</th>
            <th>Düzenle</th>
            <th>Orijinal</th>
            <th>Kime</th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.ID</td>
                <td>@x.Header</td>
                <td>@x.Context</td>
                <td>@x.Sender</td>
                <td>@x.SendTime</td>
                <td>
                    <a href="/Sirket/MesajSil/@x.ID" class="btn btn-danger">
                        <i class="fas fa-trash"></i> Sil
                    </a>
                </td>
                <td>
                    <a href="/Sirket/MesajDuzenle/@x.ID" class="btn btn-warning">
                        <i class="fas fa-pen"></i> Düzenle
                    </a>
                </td>
                <td>
                    @if (x.IsOriginal == Convert.ToBoolean(true))
                    {
                        <p>Düzenlenmemiş</p>
                    }
                    else
                    {
                        <p>Düzenlenmiş</p>
                    }
                </td>
                <td>
                    @if (x.PersonelAdi == null)
                    {
                        <p>Herkese</p>
                    }
                    else
                    {
                        <p>@x.PersonelAdi</p>
                    }

                </td>
            </tr>
        }

    </table>
</div>

IsTakip/Views/Sirket/PersonelDuzenle.cshtml
@model IsTakip.Models.TBL_PERSON

@{
    ViewBag.Title = "PersonelDuzenle";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<h2 class="text-center">Personeli Düzenle</h2>

<div class="container">
    <form method="post">
        @Html.Label("Personel Adı-Soyadı")
        @Html.TextBoxFor(x => x.personelAdSoyad, new { @class = "form-control" })
        <br />
        @Html.Label("Personel Kullanıcı Adı")
        @Html.TextBoxFor(x => x.personelUsername, new { @class = "form-control" })
        <br />
        @Html.Label("Personel Şifresi")
        @Html.TextBoxFor(x => x.personelPasswd, new { @class = "form-control" })
        <br />
        @Html.Label("Personel Yetki")
        <div class="form-check">
            @Html.RadioButtonFor(x => x.personelYetkiID, 1, new { @class = "form-check-input", id = "yonetici" })
            <label class="form-check-label" for="yonetici">Yönetici</label>
        </div>
        <div class="form-check">
            @Html.RadioButtonFor(x => x.personelYetkiID, 2, new { @class = "form-check-input", id = "calisan"})
            <label class="form-check-label" for="calisan">Çalışan</label>
        </div>

        <br />
        <button type="submit" class="btn btn-success">Kaydet</button>
    </form>
</div>

IsTakip/Views/Sirket/PersonelEkle.cshtml
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<h2 class="text-center">Personel Ekle</h2>

<br />

<form method="post">
    <input type="text" class="form-control" name="personelAdSoyad" placeholder="Personel adını girin" required/>
    <br />
    <input type="text" class="form-control" name="personelUsername" placeholder="Personel kullanıcı adını girin" required/>
    <br />
    <input type="text" class="form-control" name="personelPasswd" placeholder="Personel şifresini girin" required/>
    <br />
    <label>Personel yetkilendirme</label> <br />
    <input type="radio" class="form" name="personelYetkiID" value="1" checked />Yönetici <br />
    <input type="radio" class="form" name="personelYetkiID" value="2" />Çalışan
    <br />
    <label>Personel birimi</label> <br />
    <input type="radio" class="form" name="personelBirimID" value="1" checked /> Yönetim <br />
    <input type="radio" class="form" name="personelBirimID" value="2" /> Tamir ve Bakım <br />
    <input type="radio" class="form" name="personelBirimID" value="3" /> Atölye
    <br />
    <button class="btn btn-primary">Personeli Kaydet</button>
</form>

IsTakip/Views/Sirket/PersonelListele.cshtml
@model IsTakip.Models.PersonelViewModel

@{
    ViewBag.Title = "PersonelListele";
    Layout = "~/Views/Shared/_LayoutYonetici.cshtml";
}

<h2 class="text-center">Personel Listesi</h2>
<br />

<div class="container">
    <p><i style="user-select: none; font-size: 12px">Dikkat! Bu sekmede yapacağınız işlemlerin geri dönüşü olmayacaktır.</i></p>
    <div class="row">
        <div class="col-5">
            <h4 class="text-center">Yönetici Listesi</h4>

            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Ad-Soyad</th>
                    <th>Kullanıcı Adı</th>
                    <th>Şifre</th>
                    <th>Sil</th>
                    <th>Düzenle</th>
                </tr>
                @foreach (var x in Model.Yoneticiler)
                {
                    <tr>
                        <td>@x.ID</td>
                        <td>@x.personelAdSoyad</td>
                        <td>@x.personelUsername</td>
                        <td>@x.personelPasswd</td>
                        <td>
                            <form action="/Sirket/PersonelSil/@x.ID" method="post">
                                <button type="submit" class="btn btn-danger">Sil</button>
                            </form>
                        </td>
                        <td>
                            <a href="/Sirket/PersonelDuzenle/@x.ID" class="btn btn-warning">Düzenle</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-5 ms-auto">
            <h4 class="text-center">Personel Listesi</h4>
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Ad-Soyad</th>
                    <th>Kullanıcı Adı</th>
                    <th>Şifre</th>
                    <th>Sil</th>
                    <th>Düzenle</th>
                </tr>
                @foreach (var x in Model.Personeller)
                {
                    <tr>
                        <td>@x.ID</td>
                        <td>@x.personelAdSoyad</td>
                        <td>@x.personelUsername</td>
                        <td>@x.personelPasswd</td>
                        <td>
                            <form action="/Sirket/PersonelSil/@x.ID" method="post">
                                <button type="submit" class="btn btn-danger">Sil</button>
                            </form>
                        </td>
                        <td>
                            <a href="/Sirket/PersonelDuzenle/@x.ID" class="btn btn-warning">Düzenle</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <form action="/Sirket/PersonelEkle/" method="get">
        <button class="btn btn-primary">Personel Ekle</button>
    </form>

</div>